//console.log("Welcome to Node JS Application");

// var event = require("events");
// var filSystem = require("fs");
// var evetEmitter = new event.EventEmitter();

// Example 1
// var f1 = function(){
//     console.log("Connection is established successfully !");
// }

// evetEmitter.on("onConnected", f1); // Attached the event handler to event
// evetEmitter.emit("onConnected");   // Trigger the event

//Example 2 
// var sendSMS =  function() {
//     console.log("Send SMS Successfully")
// }

// var sendMail = function() {
//     console.log("Send Email Successfully")
// }

// //Attach event
// evetEmitter.on("ConfirmOrder", sendMail); // Attached the event handler to event
// evetEmitter.emit("ConfirmOrder");   // Trigger the event

// console.log("----------------------------------------------------");

// //Attach one more event
// evetEmitter.on("ConfirmOrder", sendSMS); // Attached the event handler to event
// evetEmitter.emit("ConfirmOrder");   // Trigger the event

// //Detach Event 
// console.log("----------------------------------------------------");

// evetEmitter.removeListener("ConfirmOrder", sendMail); // Attached the event handler to event
// evetEmitter.emit("ConfirmOrder");   // Trigger the event

// Example 3 File Stream Events
// Read Stream

// var streamReader = filSystem.createReadStream('input_data.txt');
// streamReader.setEncoding('UTF8');

// var strContent = "";

// // data is predefined function
// streamReader.on("data", function(file_data){

//     //console.log(file_data);
//     strContent += file_data;
// });

// // end is predefined function
// streamReader.on("end", function(file_data){
//     console.log(strContent);
//     console.log("File reading process completed !");
// });

// // error is predefined function
// streamReader.on("error", function(err){
//     console.log("Error has corrured while loading the file !");
//     console.log(err.stack);
// })

// Example 4 - Write Steam
// var data = "Write Stream usage in Node Js-3\n";

// // Add and Overwrite the data in file
// //var streamWritter = filSystem.createWriteStream('Output_data.txt');

// // Add and Append the data in file
// var streamWritter = filSystem.createWriteStream('Output_data.txt', {flags:'a'});
// streamWritter.write(data, 'utf8');

// streamWritter.end();

// // finish event
// streamWritter.on("finish", function(){
//     console.log("write Complete !");
// })

// // error event 
// streamWritter.on("error", function(err){
//     console.log(err.stack);
// })

// // This log will execute and not wait for Proces to finish
// console.log("Program completed");

//Output
//Program completed
//write Complete !

// Example Next -  Web Server Example

// var http = require('http');

// http.createServer( function (req, res) 
// {
//     res.writeHead(200, {'Content-Type': 'text/html'});
//     res.write("Hello World");
//     res.end();	
// }).listen(3001);

// console.log("Node Server is started. Url:  http://localhost:3001");

// Example Express JS Server
// var express = require('express');

// var app=express();

// app.get( '/',function (req,res)
// {
// 	res.send('<h1>Web Application Development using Express!</h1>');
// });

// var server=app.listen(3002,function() {});

// console.log("Server Started. URL:http://localhost:3002");

// Example Login Page - 
// var express = require('express');

// // npm i body-parser   --save
// var bodyParser = require("body-parser");

// var app=express();
// app.use(bodyParser.urlencoded({extended : false}));


// app.get('/',function(req,res)
// {
// 	var str  = "<h3 align='center'>Welcome to Express JS Application</h3>";
// 	str +=  "<hr/>";
// 	str +=  "<a  href='Login'>Login</a>";
// 	res.send(str);
// });

// app.get('/Login',function(req,res)
// {	 
//     res.sendFile( __dirname + "\\Login.html");
// });

// app.post('/Login',function(req,res)
// {	 
//     let uid = req.body.txtUid;
//     let pwd = req.body.txtPwd;

//     if(uid == "admin"  && pwd  == "admin123")
// 	{
// 		str  = "<h1 style='color:Green;'>Welcome to Admin</h1>";		
// 	}
// 	else
// 	{
// 		str  = "<h1 style='color:Red;'>Invalid user id or password</h1>";
// 	}	
	
// 	res.send(str);
// });

// Example Middleware
// var myLogger = function (req, res, next) {
//     // code to perform required task
//     console.log('Message generated by myLogger middleware');
//     next();
// };

//  app.use(myLogger);




// var server=app.listen(3002,function() {});

 
// console.log("Server Started. URL:http://localhost:3002");
